export const BOOK_GROUPS = {
  Torah: ['Genesis', 'Exodus', 'Leviticus', 'Numbers', 'Deuteronomy'],
  History: ['Joshua', 'Judges', 'Ruth', '1 Samuel', '2 Samuel', '1 Kings', '2 Kings', '1 Chronicles', '2 Chronicles', 'Ezra', 'Nehemiah', 'Esther'],
  Poetry: ['Job', 'Psalms', 'Proverbs', 'Ecclesiastes', 'Song of Solomon'],
  Prophets: ['Isaiah', 'Jeremiah', 'Lamentations', 'Ezekiel', 'Daniel', 'Hosea', 'Joel', 'Amos', 'Obadiah', 'Jonah', 'Micah', 'Nahum', 'Habakkuk', 'Zephaniah', 'Haggai', 'Zechariah', 'Malachi'],
  Gospels: ['Matthew', 'Mark', 'Luke', 'John'],
  Epistles: ['Romans', '1 Corinthians', '2 Corinthians', 'Galatians', 'Ephesians', 'Philippians', 'Colossians', '1 Thessalonians', '2 Thessalonians', '1 Timothy', '2 Timothy', 'Titus', 'Philemon', 'Hebrews', 'James', '1 Peter', '2 Peter', '1 John', '2 John', '3 John', 'Jude', 'Revelation'],
};

export const AMHARIC_BOOK_NAMES = {
  Genesis: 'ኦሪት ዘፍጥረት',
  Exodus: 'ኦሪት ዘጸአት',
  Leviticus: 'ኦሪት ዘሌዋውያን',
  Numbers: 'ኦሪት ዘኍልቍ',
  Deuteronomy: 'ኦሪት ዘዳግም',
  Joshua: 'መጽሐፈ ኢያሱ ወልደ ነዌ',
  Judges: 'መጽሐፈ መሳፍንት',
  Ruth: 'መጽሐፈ ሩት',
  '1 Samuel': '1ኛ ሳሙኤል',
  '2 Samuel': '2ኛ ሳሙኤል',
  '1 Kings': '1ኛ ነገሥት',
  '2 Kings': '2ኛ ነገሥት',
  '1 Chronicles': '1ኛ ዜና መዋዕል',
  '2 Chronicles': '2ኛ ዜና መዋዕል',
  Ezra: 'መጽሐፈ ዕዝራ',
  Nehemiah: 'መጽሐፈ ነህምያ',
  Esther: 'መጽሐፈ አስቴር',
  Job: 'መጽሐፈ ኢዮብ',
  Psalms: 'መዝሙረ ዳዊት',
  Proverbs: 'መጽሐፈ ምሳሌ',
  Ecclesiastes: 'መጽሐፈ መክብብ',
  'Song of Solomon': 'መኃልየ መኃልይ ዘሰሎሞን',
  Isaiah: 'ትንቢተ ኢሳይያስ',
  Jeremiah: 'ትንቢተ ኤርምያስ',
  Lamentations: 'ሰቆቃወ ኤርምያስ',
  Ezekiel: 'ትንቢተ ሕዝቅኤል',
  Daniel: 'ትንቢተ ዳንኤል',
  Hosea: 'ትንቢተ ሆሴዕ',
  Joel: 'ትንቢተ ኢዩኤል',
  Amos: 'ትንቢተ አሞጽ',
  Obadiah: 'ትንቢተ አብድዩ',
  Jonah: 'ትንቢተ ዮናስ',
  Micah: 'ትንቢተ ሚክያስ',
  Nahum: 'ትንቢተ ናሆም',
  Habakkuk: 'ትንቢተ ዕንባቆም',
  Zephaniah: 'ትንቢተ ሶፎንያስ',
  Haggai: 'ትንቢተ ሐጌ',
  Zechariah: 'ትንቢተ ዘካርያስ',
  Malachi: 'ትንቢተ ሚልክያስ',
  Matthew: 'ወንጌል ዘማቴዎስ',
  Mark: 'ወንጌል ዘማርቆስ',
  Luke: 'ወንጌል ዘሉቃስ',
  John: 'ወንጌል ዘዮሐንስ',
  Acts: 'የሐዋርያት ሥራ',
  Romans: 'ወደ ሮሜ ሰዎች',
  '1 Corinthians': '1ኛ ወደ ቆሮንቶስ ሰዎች',
  '2 Corinthians': '2ኛ ወደ ቆሮንቶስ ሰዎች',
  Galatians: 'ወደ ገላትያ ሰዎች',
  Ephesians: 'ወደ ኤፌሶን ሰዎች',
  Philippians: 'ወደ ፊልጵስዩስ ሰዎች',
  Colossians: 'ወደ ቆላስይስ ሰዎች',
  '1 Thessalonians': '1ኛ ወደ ተሰሎንቄ ሰዎች',
  '2 Thessalonians': '2ኛ ወደ ተሰሎንቄ ሰዎች',
  '1 Timothy': '1ኛ ወደ ጢሞቴዎስ',
  '2 Timothy': '2ኛ ወደ ጢሞቴዎስ',
  Titus: 'ወደ ቲቶ',
  Philemon: 'ወደ ፊልሞና',
  Hebrews: 'ወደ ዕብራውያን',
  James: 'የያዕቆብ መልእክት',
  '1 Peter': '1ኛ የጴጥሮስ መልእክት',
  '2 Peter': '2ኛ የጴጥሮስ መልእክት',
  '1 John': '1ኛ የዮሐንስ መልእክት',
  '2 John': '2ኛ የዮሐንስ መልእክት',
  '3 John': '3ኛ የዮሐንስ መልእክት',
  Jude: 'የይሁዳ መልእክት',
  Revelation: 'የዮሐንስ ራእይ',
};
