"""Add working_hours and time_lap_minutes to plan

Revision ID: 7ff3637a87d7
Revises: 002
Create Date: 2026-02-27 17:30:37.637143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ff3637a87d7'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('working_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('plans', sa.Column('time_lap_minutes', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_units_plan'), 'reading_units', ['plan_id'], unique=False)
    op.create_index(op.f('idx_plans_device'), 'plans', ['device_id'], unique=False)
    op.drop_column('plans', 'time_lap_minutes')
    op.drop_column('plans', 'working_hours')
    op.create_unique_constraint(op.f('uq_bible_verses_book_chapter_verse'), 'bible_verses', ['book_id', 'chapter', 'verse_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_bible_verses_book_id'), 'bible_verses', ['book_id'], unique=False)
    op.create_index(op.f('idx_bible_topics_topic_index'), 'bible_topics', ['topic_index'], unique=False)
    op.create_index(op.f('idx_bible_topic_verses_topic_id'), 'bible_topic_verses', ['topic_id'], unique=False)
    op.create_index(op.f('idx_bible_books_book_number'), 'bible_books', ['book_number'], unique=True)
    # ### end Alembic commands ###
